base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('post/<slug:slug>/', views.post, name='post'),
    path('profile/', views.home, name='profile'),
    
    #CRUD PATHS
	path('create_post/', views.createPost, name="create_post"),
    path('update_post/<slug:slug>/', views.updatePost, name="update_post"),
    path('delete_post/<slug:slug>/', views.deletePost, name="delete_post"),
    
    # Email
    path('send_email/', views.sendEmail, name='send_email'),
    
    # Login, Register & Logout
    path('login/', views.loginPage, name="login"),
	path('register/', views.registerPage, name="register"),
	path('logout/', views.logoutUser, name="logout"),
]

dheerajportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('base.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),  # This handles the upload functionality
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field  

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="images", default="/images/placeholder.png")
    github_url = models.URLField(
        "GitHub repository URL",
        max_length=500,
        null=True,
        blank=True,
        help_text="Optional. Example: https://github.com/username/repo",
    )
    body = CKEditor5Field(config_name='extends')
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.headline

    def save(self, *args, **kwargs):
        # Generate slug if not set
        if self.slug is None or self.slug.strip() == "":
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = f"{slugify(self.headline)}-{count}"
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug = slug

        super().save(*args, **kwargs)
        

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader  import render_to_string

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

from .models import *
from .form import *
from .filters import *

import os              
from dotenv import load_dotenv
load_dotenv()               #for 'os.environ.get("MY_EMAIL")' in sendEmail view - so that mail is sent to themselves.

# Create your views here.
def home(request):
    posts = Post.objects.filter(active=True, featured=True)[0:3]
    return render(request, 'base/index.html', {'posts':posts})

def posts(request):
    posts = Post.objects.filter(active = True)  
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs
    
    page = request.GET.get('page')
    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'base/posts.html', {'posts':posts, 'myFilter':myFilter})

def post(request, slug):
	post = Post.objects.get(slug=slug)
	return render(request, 'base/post.html', {'post' : post})

def profile(request):
    return render(request, 'base/profile.html')


# CRUD VIEWS
@login_required(login_url='home')
def createPost(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid:
            form.save()
            return redirect('posts')

    return render(request, 'base/post_form.html', {'form':form})

@login_required(login_url='home')
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES,instance=post)
        if form.is_valid:
            form.save()
            return redirect('post', slug=post.slug)

    return render(request, 'base/post_form.html', {'form':form})

@login_required(login_url='home')
def deletePost(request, slug):
    post = Post.objects.get(slug=slug)

    if request.method == 'POST':
        post.delete()
        return redirect('posts')

    return render(request, 'base/delete.html', {'item':post})


# Email Sending
def sendEmail(request):

	if request.method == 'POST':

		template = render_to_string('base/email_template.html', {
			'name':request.POST['name'],
			'email':request.POST['email'],
			'message':request.POST['message'],
			})

		email = EmailMessage(
			request.POST['subject'],           # Subject from the form
			template,                          # Email body (rendered HTML template)
			settings.EMAIL_HOST_USER,          # Sender email from settings
			[os.environ.get("MY_EMAIL")]       # Recipient email(s)
			)

		email.fail_silently=False
		email.send()

	return render(request, 'base/email_sent.html')


# Login, Register & Logout
def loginPage(request):
	if request.user.is_authenticated:
		return redirect('home')

	if request.method == 'POST':
		email = request.POST.get('email')
		password =request.POST.get('password')

		#Little Hack to work around re-building the usermodel
		try:
			user = User.objects.get(email=email)  # fetch the user by email
			user = authenticate(request, username=user.username, password=password) # authenticate
		except: 
			messages.error(request, 'User with this email does not exists')
			return redirect('login')
			
		if user is not None:
			login(request, user)
			return redirect('home')
		else:
			messages.error(request, 'Email OR password is incorrect')

	context = {}
	return render(request, 'base/login.html', context)

def registerPage(request):
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')  # Get the email from the form
            # Check if the email already exists
            if User.objects.filter(email=email).exists():
                messages.error(request, 'Email already exists! Please choose a different one.')
                return redirect('register')  # Redirect back to the registration page
            user = form.save(commit=False)
            user.save()
            messages.success(request, 'Account successfuly created!')
            
            user = authenticate(request, username=user.username, password=request.POST['password1']) #Attempts to log the user in after registration.

            if user is not None:
                login(request, user)          # If authentication is successful, the user is logged in immediately using Django's login() method.
                
            next_url = request.GET.get('next')  # Handles redirection - 'next'in (?next=/some/url) specifies where to go after login.
            if next_url == '' or next_url == None: 
                next_url = 'home'
            return redirect(next_url)
        else:
            messages.error(request, 'An error has occured with registration')
    context = {'form':form}
    return render(request, 'base/register.html', context)

def logoutUser(request):
	logout(request)
	return redirect('home')

base/templates/base/delete.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<div class="main-container">
	<form method="POST" action="">
		{% csrf_token %}

		<p>Are you sure you want to delete {{item}}?</p>
        <input class="btn btn-danger" type="submit" value="Confirm"> <br><br>
		<a class="btn btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
	</form>
</div>

{% endblock content %}

base/templates/base/email_sent.html
{% extends 'base/main.html' %}

{% block content %}

<style type="text/css">
	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
	}

	#success-box p{
		font-size: 18px;
	}

</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h1>Thanks for reaching out!</h1>
		<p>Your message was successfully sent. I will do my best to get back to you in a timely manner :)</p>
		<a id="back-btn" class="btn btn-success" href="{% url 'home' %}">BACK TO HOME PAGE</a>
	</div>
</div>

{% endblock content %}

base/templates/base/email_template.html
name: {{name}}
email: {{email}}

message:
{{message}}

base/templates/base/home.html
{% extends "base/main.html" %}

{% block content %}
this is home
{% endblock content %}
    

base/templates/base/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>V. SAI DHEERAJ</title>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>

	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hi, I'm V. SAI DHEERAJ</h1>
			</div>


			<div class="intro-wrapper">
				{% include 'base/navbar.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/DHEERAJ.jpg' %}">
					<h5 style="text-align: center;line-height: 0;">Personalize Theme</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
					</div>

					<p id="settings-note">*Theme settings will be saved for<br>your next visit</p>
				</div>

				<div class="right-column">

					<div id="preview-shadow">
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>What I Do</h3>
							<p>IIIT Sonipat CSE student, 
								with strong problem-solving, project management, analytics, 
								and logical thinking skills seeks opportunity 
								to leverage Python full-stack development experience.</p>
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">

			<div class="about-wrapper">
				<div class="about-me">
					<h4>More about me</h4>

					<p>I build new projects just to tickle my brain and love learning new tech.</p>

					<p>While I keep busy doing projects, I take interviews in search of a great team & projects that interest me.</p>


					<hr>

					<h4>TOP EXPERTISE</h4>

					<p>Backend developer with primary focus on Django: <br> <a target="_blank" href="{% static 'v sai dheeraj - resume.pdf' %}">Download Resume</a></p>

					<div id="skills">
						<ul>
							<li>Python</li>
							<li>Django</li>
							<li>Flask</li>
							<li>JavaScript</li>
							<li>jQuery</li>
							<li>PostgreSQL/MySQL</li>
						</ul>

						<ul>
							<li>Postman</li>
							<li>REST API</li>
							<li>Docker</li>
							<li>AWS (Lambda/EC2/RDS/S3)</li>
							<li>GitHub</li>
							<li>HTML/CSS</li>
						</ul>

					</div>

					<p class="text-muted" style="margin-top:8px;font-size:12px;">This portfolio is built entirely with Python and Django.</p>
				</div>

				
				<div class="social-links">
					<img id="social_img" src="{% static 'images/follow.png' %}">
					<h3>Find me on - </h3>

					<a target="_blank" href="https://www.linkedin.com/in/vsaidheeraj/">LinkedIn: Sai Dheeraj</a>
					<br>
					<a target="_blank" href="https://github.com/vsdheeraj">GitHub: @vsdheeraj</a>
					<br>
					<a target="_blank" href="https://www.instagram.com/dheerajpawaar/">Instagram: @dheerajpawaar</a>
				</div>
			</div>

		</div>
	</section>

	<section class="s1">
		<div class="main-container">
			<h3 style="text-align: center;">Some of my past projects</h3>

			<div class="post-wrapper">
				{% for post in posts %} 
				<div>
					<div class="post">
						<img class="thumbnail" src="{{post.thumbnail.url}}">
						<div class="post-preview">
							<h6 class="post-title">{{post.headline}}</h6>
							<p class="post-intro">{{post.sub_headline}}</p>
							<a href="{%  url 'post' post.slug %}">Read More</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>

			<p align="center">
				<a href="{% url 'posts' %}">View More</a>
			</p>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">
			<a href=""></a>
			<h3 style="text-align: center;">Get In Touch</h3>

			<form id="contact-form" method="POST" action="{% url 'send_email' %}">
				{% csrf_token %}
				<a name="contact"></a>

				<label>Name</label>
				<input required class="input-field" type="text" name="name">

				<label>Subject</label>
				<input required class="input-field" type="text" name="subject">

				<label>Email</label>
				<input required class="input-field" type="text" name="email">

				<label>Message</label>
				<textarea required class="input-field" name="message"></textarea>

				<input id="submit-btn" type="submit" value="Send">
			</form>
		</div>
	</section>  

	<script type="text/javascript">
		let static = "{% static 'css' %}"
	</script>

	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

base/templates/base/login.html
{% include 'base/main.html' %}
{% load static %}
{% block content %}


<section id="login-page-wrapper">
	<div id="login-form-wrapper">
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'success' %}
					<div class="alert alert-success" role="alert">
						<span>{{message}}</span>					
					</div>
				{% elif message.tags == 'error' %}
					<div class="alert alert-danger" role="alert">
						<span>{{message}}</span>					
					</div>
				{% endif %}
			{% endfor %}
		{% endif %}

		<h3 style="text-align: center">Member Login</h3>
		<hr>
		<form method="POST">
			{% csrf_token %}
			<label>Email</label>
			<input class="form-control" type="email" name="email">
			<br>
			<label>Password</label>
			<input class="form-control" type="password" name="password">
			<br>
			<input class="btn btn-primary btn-lg btn-block" type="submit" value="Login">
		</form>

		<br>
		<p>Dont have an account? <a href="{% url 'register' %}">Register</a></p>
	</div>
</section>

{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>V. Sai Dheeraj</title>

	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
</head>
<body>

	{% include 'base/navbar.html' %}

	{% block content %}
	<!-- Content goes here -->
	{% endblock content %}

</body>
</html>

base/templates/base/navbar.html
{% load static %}
<div class="nav-wrapper">

	<a href="{% url 'home' %}">
		<div class="dots-wrapper">
			<div id="dot-1" class="browser-dot"></div>
			<div id="dot-2" class="browser-dot"></div>
			<div id="dot-3" class="browser-dot"></div>
		</div>
	</a>
	

	<ul id="navigation">
		<h2  id="close-btn" style="text-align: center">X</h2>
		<li><a href="{% url 'home' %}#contact">Contact</a></li>
		{% if request.user.is_authenticated %}
			{% comment %} <li><a href="{% url 'account' %}"> Account</a></li> {% endcomment %}
			<li><a href="{% url 'logout' %}">Logout</a></li>
		{% else %}
			<li><a href="{% url 'login' %}">Login</a></li>
			<li><a href="{% url 'register' %}">Register</a></li>
		{% endif %}
	</ul>

	<img id="menu-icon" src="{% static 'images/menu.png' %}">

</div>


<script type="text/javascript">
	let menu = 'closed' 

	let menuIcon = document.getElementById('menu-icon')
	let navigation = document.getElementById('navigation')
	let closeBtn = document.getElementById('close-btn')

	menuIcon.addEventListener('click', toggleMenu)
	closeBtn.addEventListener('click', toggleMenu)


	function toggleMenu(){
		if (menu == 'closed'){
			navigation.style.display = 'block'
			closeBtn.style.display = 'block'
			menu = 'open'
		}else{
			navigation.style.display = 'none'
			closeBtn.style.display = 'none'
			menu = 'closed'
		}
	}

	    
	// Attaching the event listener function to window's resize event
	
	window.addEventListener("resize", function(){
		let width = document.documentElement.clientWidth;
		if(width > 1080){
				navigation.style.display = 'block'
		}else{
				navigation.style.display = 'none'
		}
		menu = 'closed'
		closeBtn.style.display = 'none'
	});
	
</script>

base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	img{
		max-width: 100%;
		object-fit: cover;
	}

	.featured_image{
		margin-top: 20px;
		margin-bottom: 20px;
		height: 250px;
		width: 250px
	}

	.post-container{
			width: 1000px;
			margin: 0 auto;
			padding-top: 20px;
			padding-bottom: 20px;
	}

	.github-btn{
		margin-top: 10px;	
		border: 1px solid #24292e;
		color: #24292e;
		background: #ffffff;
		padding: 6px 12px;
		border-radius: 6px;
		font-weight: 600;
		display: inline-flex;
		align-items: center;
		gap: 8px;
		transition: background-color .15s ease, color .15s ease, border-color .15s ease, box-shadow .15s ease;
		text-decoration: none;
	}

	.github-btn:hover{
		background: #24292e;
		color: #ffffff;
		text-decoration: none;
	}

	.comments-wrapper{
		margin-top: 50px;
		padding: 10px;
		border:1px solid var(--borderColor);
		-webkit-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		-moz-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
	}

	.comment{
		display: flex;
		padding: 15px;
	}

	.comment-author{
		font-size: 14px;
		font-weight: 700;
		color: rgb(30, 174, 219) !important;
		margin: 2px;
	}

	.author-pic{
		width: 50px;
		height: 50px;
		border-radius: 50%;
		margin-right: 10px;
	}

	.comment-body{

		font-size: 14px;
	}

	@media screen and (max-width: 900px){
		.post-container{
			width: 90%;
		}
	}
</style>

<div class="post-container">

	<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a><br> <br>

	{% if request.user.is_authenticated %}
		 <a class="btn btn-sm btn-primary" href="{% url 'update_post' post.slug %}">Edit</a>
		 <a class="btn btn-sm btn-danger" href="{% url 'delete_post' post.slug %}">Delete</a> <br>
	{% endif %}

	<img class="featured_image" src="{{post.thumbnail.url}}">
	<br>
	{% for tag in post.tags.all %}
		<span class="tag">{{tag}}</span>
	{% endfor %}

	{% if post.github_url %}
		<p>
			<a class="github-btn" href="{{ post.github_url }}" target="_blank" rel="noopener noreferrer">View on GitHub</a>
		</p>
	{% endif %}
	<hr>
	<h1>{{post.headline}}</h1>
	<h4>{{post.sub_headline}}</h4>
	<p>{{post.body|safe}}</p>

	{% comment %} <div class="comments-wrapper">
		<h5>Comments: {{post.postcomment_set.all.count}}</h5>
		<hr>
		<!--
			- Not logged in, output form and say "Register to comment and give room for a message"
			- When given username 
		-->
		{% if request.user.is_authenticated %}
		<form action="" method="POST">
			{% csrf_token %}
			<textarea required class="form-control" placeholder="Leave a comment..." name="comment"></textarea>
			<br>
			<input class="btn btn-info" type="submit" value="Submit">
		</form>
		{% else %}
			<p>Create an account to comment:</p>
			<a class="btn btn-primary" href="{% url 'register' %}">Register/Login</a>
		{% endif %}

		<hr>
		{% for comment in post.postcomment_set.all %}
			<div class="comment">
				<img class="author-pic" src="{{comment.author.profile_pic.url}}">
				<div>
					<p class="comment-author">{{comment.author}}: {{comment.created|date:"M-d-Y"}}</p>
					<p class="comment-body">{{comment.body}}</p>
				</div>
			</div>
		{% endfor %}
	</div>
</div> {% endcomment %}

{% endblock content %}

base/templates/base/post_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
	#div_id_tags > div{
		max-height: 100px;
		overflow-y: scroll;
		border:1px solid #888;
		padding: 5px;
		border-radius: 5px;
	}
</style>
<div class="main-container">
	<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
	<h3>Post Form</h3>
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form|crispy }}
        {{ form.media }}
		<input class="btn btn-primary" type="submit" value="Submit Post">
		
	</form>
</div>

{% endblock content %}

base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<style type="text/css">
	#div_id_tags, #id_tags{
		overflow-y: scroll;
		max-height: 100px;
		border-radius: 5px;
		padding: 5px;
		border:1px solid #888;
	}
</style>

<div class="main-container">		
	<h1>Posts</h1>
	{% if request.user.is_authenticated %}
		<a class="btn btn-warning" href="{% url 'create_post' %}">Create Post</a>
	{% endif %}

	<form id="searchForm" method="get">
		{{myFilter.form|crispy}}
		<input class='btn btn-primary' type="submit" value="Search">
	</form>
	
	<br>

	<div class="post-wrapper">
		{% for post in posts %}
		<div>
			<div class="post">
				<img class="thumbnail" src="{{post.thumbnail.url}}">
				<div class="post-preview">
					<h6 class="post-title">{{post.headline}}</h6>
					<p class="post-intro">{{post.sub_headline}}</p>
					<a href="{% url 'post' post.slug %}">Read More</a>

					{% if post.github_url %}
						<span> | <a href="{{ post.github_url }}" target="_blank" rel="noopener noreferrer">GitHub</a></span>
					{% endif %}

					{% if request.user.is_authenticated %}
						<a href="{% url 'update_post' post.slug %}">| Edit</a>
						<a href="{% url 'delete_post' post.slug %}">| Delete</a>
					{% endif %}
					<hr>
					{% for tag in post.tags.all %}
						<span class="tag">{{tag}}</span>
					{% endfor %}
				</div>
			</div>
		</div>
		{% empty %}
			<h3>No posts found...</h3>
		{% endfor %}
	</div>
	
	<div class="row">
		
		{% if posts.has_other_pages %}

			<ul class="pagination">

				{% if posts.has_previous %}
					<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

					<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
				{% endif %}


				{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item"><a class="active page-link">{{i}}</a></li>
					{% else %}
						<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
					{% endif %}
					
				{% endfor %}


				{% if posts.has_next %}
					<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

					<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
				{% endif %}
			</ul>

		{% endif %}
	</div>
</div>


<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length > i; i++){

		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('Page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden >`
			searchForm.submit()
		})

	}
</script>

{% endblock content %}

base/templates/base/profile.html
{% extends "base/main.html" %}

{% block content %}
this is profile
{% endblock content %}
    

base/templates/base/register.html
{% include 'base/main.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<style type="text/css">
	
</style>

<section id="login-page-wrapper">
	<div id="login-form-wrapper">
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'success' %}
					<div class="alert alert-success" role="alert">
						<span>{{message}}</span>					
					</div>
				{% elif message.tags == 'error' %}
					<div class="alert alert-danger" role="alert">
						<span>{{message}}</span>					
					</div>
				{% endif %}
			{% endfor %}
		{% endif %}

		<h3 style="text-align: center">Register Account</h3>
		<hr>
		<form method="POST" action="?next={{ request.META.HTTP_REFERER }}">
			{% csrf_token %}
			{{form|crispy}}
			<input class="btn btn-primary btn-lg btn-block" type="submit" value="Login">
		</form>

		<br>
		<p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
	</div>
</section>

{% endblock content %}